

// actionTypes.js
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

export const SET_USER_USERNAME='SET_USER_USERNAME';
export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const SET_USER_DISPLAY_NAME = 'SET_USER_DISPLAY_NAME';
export const LOGOUT_USER = 'LOGOUT_USER';

